---
title: "take2"
author: "Jonathan Wu"
date: '2024-08-29'
output: html_document
---
```{r}
library(dplyr)
library(jsonlite)
library(glmnet)
```


```{r}
# data <- stream_in(file("data/Curated/FIDE_INDIVIDUAL.ndjson"))
data <- stream_in(file("data/Curated/FICS_INDIVIDUAL.ndjson"))
data$opening <- factor(data$opening)
data$result <- factor(data$result)
data$is_white <- factor(data$is_white)
data_clean <- na.omit(data)


# Prepare data for glmnet
X <- model.matrix(elo ~ opening + 
                    result + 
                    stockfish_mean + stockfish_min + stockfish_max + 
                  stockfish_std + maia_mean + maia_min + maia_max + maia_std + 
                is_white, data = data_clean)[,-1] # Removing intercept
y <- data_clean$elo

set.seed(10)

train_indices <- sample(1:nrow(X), 22000)
X_train <- X[train_indices, ]
y_train <- y[train_indices]
X_test <- X[-train_indices, ]
y_test <- y[-train_indices]


data_train <- data_clean[train_indices, ]
data_test <- data_clean[-train_indices, ]
```


```{r}
colnames(data)
```

```{r}
# Fit a Lasso model
lasso_model <- cv.glmnet(X_train, y_train, alpha = 1)  # alpha=1 for Lasso, alpha=0 for Ridge
```

```{r}
coef(lasso_model)
```


```{r}
lasso_pred <- predict(lasso_model, alpha = 1, newx = X_test)
mse_test <- mean((lasso_pred - y_test)^2)
mae_test <- sqrt(mse_test)
print(mse_test)
print(mae_test)
```










# Fitting a lineaer model

```{r}
# data <- stream_in(file("data/Curated/FIDE_INDIVIDUAL.ndjson"))
data <- stream_in(file("data/Curated/FICS_INDIVIDUAL.ndjson"))
data$opening <- factor(data$opening)
data$result <- factor(data$result)
data$is_white <- factor(data$is_white)
data_clean <- na.omit(data)

set.seed(10)

train_indices <- sample(1:nrow(X), 22000)
data_train <- data_clean[train_indices, ]
data_test <- data_clean[-train_indices, ]
```

```{r}
# Add a new level "Unknown" to the opening factor in the training data
data_train$opening <- factor(data_train$opening, levels = c(levels(data_train$opening), "Unknown"))

# For any unseen levels in the test data, convert them to "Unknown"
data_test$opening <- factor(data_test$opening, levels = levels(data_train$opening))
data_test$opening[is.na(data_test$opening)] <- "Unknown"
```



```{r}
lm_model1 <- lm(y_train ~ opening + result + stockfish_mean + stockfish_min + 
                  stockfish_max + stockfish_std + maia_mean + maia_min + 
                  maia_max + maia_std + is_white, data = data_train)
```

```{r}
lm_model2 <- step(lm_model1)
```


Some of the higher values do not fit teh normal qq plot. 
```{r}
plot(lm_model2)
```












```{r}
lm_model3 <- lm(elo ~ opening + result + stockfish_mean + I(stockfish_mean^2) + 
                  stockfish_min + stockfish_max + stockfish_std + maia_mean + I(maia_mean^2) + maia_min + 
                  maia_max + maia_std + is_white, data = data_train)
```

```{r}
lm_model4 <- step(lm_model3)
```


```{r}
plot(model4)
```


```{r}
anova(lm_model4, lm_model2)
```


```{r}
anova(lm_model4)
# summary(lm_model4)
```



```{r}
data_test2 <- data_test %>% filter(opening != "two knights") # need to remove

# Now you can use the model to predict
predictions <- predict(lm_model4, newdata = data_test2)
```



```{r}
# Proceed with your evaluation (e.g., MSE and MAE)
actual_values <- data_test2$elo
mse <- mean((predictions - actual_values)^2)
mae <- mean(abs(predictions - actual_values))

# Print results
cat("Mean Squared Error (MSE):", mse, "\n")
cat("Mean Absolute Error (MAE):", mae, "\n")
```




```{r}
lm_model5 <- lm(elo ~ result + stockfish_mean + I(stockfish_mean^2) + 
                  stockfish_min + stockfish_max + stockfish_std + maia_mean + I(maia_mean^2) + maia_min + 
                  maia_max + maia_std + is_white, data = data_train)
```

```{r}
lm_model6 <- step(lm_model5)
```



```{r}
predictions <- predict(lm_model6, newdata = data_test2)

# Proceed with your evaluation (e.g., MSE and MAE)
actual_values <- data_test2$elo
mse <- mean((predictions - actual_values)^2)
mae <- mean(abs(predictions - actual_values))

# Print results
cat("Mean Squared Error (MSE):", mse, "\n")
cat("Mean Absolute Error (MAE):", mae, "\n")
```






























